import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { NormalizedHttpError } from '../../../core/errors/normalized-http-error';
import { AppIconComponent } from '../../../shared/app-icon/app-icon.component';
import { FeedbackAlertComponent } from '../../../shared/feedback-alert/feedback-alert.component';
import { PageHeaderComponent } from '../../../shared/page-header/page-header.component';
import { OperacaoResponse } from '../models/operacao';
import { formatCivilDate, formatDecimal } from '../operacao-validators';
import { OperacoesService } from '../operacoes.service';

@Component({selector:'app-operacoes-list-page',imports:[AppIconComponent,FeedbackAlertComponent,MatButtonModule,MatCardModule,MatProgressSpinnerModule,PageHeaderComponent,RouterLink],template:`
<section class="app-page" aria-labelledby="operations-title"><app-page-header headingId="operations-title" eyebrow="Histórico" icon="operation" title="Operações" description="Compras e vendas na ordem cronológica fornecida pelo backend."><a page-header-action mat-flat-button routerLink="nova">Nova operação</a></app-page-header>
@if(error()){<app-feedback-alert variant="error" [message]="error()!.message" [details]="error()!.details"/>}
@if(loading()){<div class="app-state" role="status" aria-live="polite"><mat-spinner diameter="36"/>Carregando operações…</div>}
@else if(error()){<div class="app-state"><button mat-stroked-button type="button" (click)="load()">Tentar novamente</button></div>}
@else if(items().length===0){<div class="app-state app-surface"><span class="app-state__icon" aria-hidden="true"><app-icon name="empty"/></span><h2>Nenhuma operação registrada.</h2><p>Registre a primeira compra ou venda.</p><a mat-stroked-button routerLink="nova">Registrar a primeira</a></div>}
@else{<div class="grid" aria-label="Operações registradas">@for(item of items();track item.id){<mat-card class="operation-card" appearance="outlined"><div class="heading"><span class="type" [class.type--sell]="item.tipo==='VENDA'"><span aria-hidden="true">{{item.tipo==='COMPRA'?'＋':'−'}}</span>{{item.tipo}}</span><strong>{{item.ticker}}</strong><span>{{item.mercado}} · {{item.moeda??(item.mercado==='BRASIL'?'BRL':'USD')}}</span></div><mat-card-content><dl><div><dt>Data · ordem</dt><dd>{{date(item.dataOperacao)}} · {{item.ordemNoDia}}</dd></div><div><dt>Carteira</dt><dd>#{{item.carteiraId}}</dd></div><div><dt>Quantidade</dt><dd>{{decimal(item.quantidade)}}</dd></div><div><dt>Preço unitário</dt><dd>{{decimal(item.precoUnitario)}}</dd></div><div><dt>Valor total</dt><dd>{{decimal(item.valorTotal)}} {{item.moeda??(item.mercado==='BRASIL'?'BRL':'USD')}}</dd></div><div><dt>Corretora</dt><dd>{{item.corretoraId===null||item.corretoraId===undefined?'Sem corretora':'#'+item.corretoraId}}</dd></div></dl></mat-card-content><mat-card-actions><a mat-button [routerLink]="[item.id]" [info]="{operacao:item,origin:'/operacoes'}" [attr.aria-label]="'Ver detalhes da operação '+item.id">Ver detalhes</a></mat-card-actions></mat-card>}</div>}
</section>`,styles:[`.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,22rem),1fr));gap:1rem}.operation-card{padding:1rem;border-color:var(--app-border-subtle);border-radius:var(--app-card-radius);min-width:0}.heading{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:.65rem}.heading>span:last-child{color:var(--app-text-secondary);font-size:.75rem}.type{display:inline-flex;gap:.25rem;padding:.25rem .55rem;border-radius:999px;color:#185b38;background:#e5f3e9;font-size:.7rem;font-weight:800}.type--sell{color:#8c1d18;background:#ffedea}dl{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem;margin:1rem 0 0}dt{color:var(--app-text-secondary);font-size:.68rem;font-weight:700;text-transform:uppercase}dd{margin:.2rem 0 0;overflow-wrap:anywhere;font-weight:600}mat-card-actions{border-top:1px solid var(--app-border-subtle);margin-top:1rem}@media(max-width:30rem){.heading{grid-template-columns:auto 1fr}.heading>span:last-child{grid-column:2}dl{grid-template-columns:1fr}}`],changeDetection:ChangeDetectionStrategy.OnPush})
export class OperacoesListPageComponent{private readonly service=inject(OperacoesService);private readonly destroyRef=inject(DestroyRef);protected readonly items=signal<OperacaoResponse[]>([]);protected readonly loading=signal(true);protected readonly error=signal<NormalizedHttpError|null>(null);protected readonly date=formatCivilDate;protected readonly decimal=formatDecimal;constructor(){this.load();}protected load():void{this.loading.set(true);this.error.set(null);this.service.listar().pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:v=>this.items.set(v),error:e=>this.error.set(e)});}}
