import { CorretoraNamesService } from '../../corretoras/corretora-names.service';
import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { MatButtonModule } from '@angular/material/button';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { RouterLink } from '@angular/router';
import { finalize } from 'rxjs';
import { NormalizedHttpError } from '../../../core/errors/normalized-http-error';
import { AppIconComponent } from '../../../shared/app-icon/app-icon.component';
import { FeedbackAlertComponent } from '../../../shared/feedback-alert/feedback-alert.component';
import { PageHeaderComponent } from '../../../shared/page-header/page-header.component';
import { OperacaoResponse } from '../models/operacao';
import { formatCivilDate, formatMoney, formatOperationQuantity } from '../operacao-validators';
import { OperacoesService } from '../operacoes.service';

@Component({providers:[CorretoraNamesService],selector:'app-operacoes-list-page',imports:[AppIconComponent,FeedbackAlertComponent,MatButtonModule,MatProgressSpinnerModule,PageHeaderComponent,RouterLink],template:`
<section class="app-page" aria-labelledby="operations-title"><app-page-header headingId="operations-title" eyebrow="Histórico" icon="operation" title="Operações" description="Compras e vendas de todas as carteiras, em ordem cronológica."><a page-header-action mat-flat-button routerLink="nova">Nova operação</a></app-page-header>
@if(error()){<app-feedback-alert variant="error" [message]="error()!.message" [details]="error()!.details"/>}
@if(loading()){<div class="app-state" role="status" aria-live="polite"><mat-spinner diameter="36"/>Carregando operações…</div>}
@else if(error()){<div class="app-state"><button mat-stroked-button type="button" (click)="load()">Tentar novamente</button></div>}
@else if(items().length===0){<div class="app-state app-surface"><span class="app-state__icon" aria-hidden="true"><app-icon name="empty"/></span><h2>Nenhuma operação registrada.</h2><p>Registre a primeira compra ou venda.</p><a mat-stroked-button routerLink="nova">Registrar a primeira</a></div>}
@else{<table class="collection-table" role="table"><caption>Operações registradas</caption><thead role="rowgroup"><tr role="row"><th scope="col" role="columnheader">Ativo</th><th scope="col" role="columnheader">Tipo</th><th scope="col" role="columnheader">Data · ordem</th><th scope="col" role="columnheader">Carteira</th><th scope="col" role="columnheader" class="numeric">Quantidade</th><th scope="col" role="columnheader" class="numeric">Preço unitário</th><th scope="col" role="columnheader" class="numeric">Valor total</th><th scope="col" role="columnheader">Corretora</th><th scope="col" role="columnheader">Ações</th></tr></thead><tbody role="rowgroup">@for(item of items();track item.id){<tr role="row"><th scope="row" role="rowheader"><span class="cell-label" aria-hidden="true">Ativo</span>{{item.ticker}}<small>{{item.mercado}} · {{item.moeda??(item.mercado==='BRASIL'?'BRL':'USD')}}</small></th><td role="cell"><span class="cell-label" aria-hidden="true">Tipo</span>{{item.tipo}}</td><td role="cell"><span class="cell-label" aria-hidden="true">Data · ordem</span>{{date(item.dataOperacao)}} · ordem {{item.ordemNoDia}}</td><td role="cell"><span class="cell-label" aria-hidden="true">Carteira</span>#{{item.carteiraId}}</td><td role="cell" class="numeric"><span class="cell-label" aria-hidden="true">Quantidade</span>{{quantity(item.quantidade,item.mercado)}}</td><td role="cell" class="numeric"><span class="cell-label" aria-hidden="true">Preço unitário</span>{{money(item.precoUnitario,item.moeda??(item.mercado==='BRASIL'?'BRL':'USD'))}}</td><td role="cell" class="numeric"><span class="cell-label" aria-hidden="true">Valor total</span>{{money(item.valorTotal,item.moeda??(item.mercado==='BRASIL'?'BRL':'USD'))}}</td><td role="cell"><span class="cell-label" aria-hidden="true">Corretora</span>{{brokerNames.name(item.corretoraId)}}</td><td role="cell"><span class="cell-label" aria-hidden="true">Ações</span><a [routerLink]="[item.id]" [info]="{operacao:item,origin:'/operacoes'}" [attr.aria-label]="'Ver detalhes da operação '+item.id">Ver detalhes</a></td></tr>}</tbody></table>}
</section>`,styleUrl:'../../../shared/collection/collection.scss',styles:[],changeDetection:ChangeDetectionStrategy.OnPush})
export class OperacoesListPageComponent{protected readonly brokerNames=inject(CorretoraNamesService);private readonly service=inject(OperacoesService);private readonly destroyRef=inject(DestroyRef);protected readonly items=signal<OperacaoResponse[]>([]);protected readonly loading=signal(true);protected readonly error=signal<NormalizedHttpError|null>(null);protected readonly date=formatCivilDate;protected readonly quantity=formatOperationQuantity;protected readonly money=formatMoney;constructor(){this.load();}protected load():void{this.loading.set(true);this.error.set(null);this.service.listar().pipe(finalize(()=>this.loading.set(false)),takeUntilDestroyed(this.destroyRef)).subscribe({next:v=>{this.items.set(v);this.brokerNames.loadFor(v);},error:e=>this.error.set(e)});}}
