spring.application.name=gestaoacoes

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

integration.brasil-api.base-url=${BRASIL_API_BASE_URL:https://brasilapi.com.br}
integration.brasil-api.connect-timeout=${BRASIL_API_CONNECT_TIMEOUT:2s}
integration.brasil-api.read-timeout=${BRASIL_API_READ_TIMEOUT:5s}

integration.via-cep.base-url=${VIA_CEP_BASE_URL:https://viacep.com.br}
integration.via-cep.connect-timeout=${VIA_CEP_CONNECT_TIMEOUT:2s}
integration.via-cep.read-timeout=${VIA_CEP_READ_TIMEOUT:5s}
