import { ComponentFixture, TestBed } from '@angular/core/testing';
import { provideRouter, Router } from '@angular/router';
import { of, Subject, throwError } from 'rxjs';
import { NormalizedHttpError } from '../../../core/errors/normalized-http-error';
import { AcoesService } from '../acoes.service';
import { AcaoResponse } from '../models/acao';
import { AcoesListPageComponent } from './acoes-list-page.component';

const BR:AcaoResponse={id:1,ticker:'PETR4',nomeEmpresa:'Petrobras',mercado:'BRASIL',moeda:'BRL',cotacaoAtual:30,dataHoraCotacao:'2026-08-29T12:00:00Z'};
const US:AcaoResponse={id:2,ticker:'AAPL',nomeEmpresa:'Apple',mercado:'EUA',moeda:'USD',cotacaoAtual:200,dataHoraCotacao:'2026-08-29T13:00:00Z'};
const failure=(status:number,code:string|null,message='Falha',details={})=>({status,code,message,details}) as NormalizedHttpError;

describe('AcoesListPageComponent',()=>{let fixture:ComponentFixture<AcoesListPageComponent>;let service:{listar:ReturnType<typeof vi.fn>;buscarPorTickerEMercado:ReturnType<typeof vi.fn>};
 beforeEach(async()=>{service={listar:vi.fn().mockReturnValue(of([US,BR])),buscarPorTickerEMercado:vi.fn().mockReturnValue(of(BR))};await TestBed.configureTestingModule({imports:[AcoesListPageComponent],providers:[provideRouter([]),{provide:AcoesService,useValue:service}]}).compileComponents();vi.spyOn(TestBed.inject(Router),'navigate').mockResolvedValue(true);fixture=TestBed.createComponent(AcoesListPageComponent);fixture.detectChanges();});
 const component=()=>fixture.componentInstance as unknown as {searchForm:{controls:{ticker:{setValue(v:string):void};mercado:{setValue(v:'BRASIL'|'EUA'|null):void}}};search():void;clearSearch():void;load():void};
 it('loads cards in backend order with accessible navigation and no quote update',()=>{const text=fixture.nativeElement.textContent;expect(service.listar).toHaveBeenCalledTimes(1);expect(text.indexOf('AAPL')).toBeLessThan(text.indexOf('PETR4'));expect(fixture.nativeElement.querySelectorAll('mat-card')).toHaveLength(2);expect(fixture.nativeElement.querySelector('table')).toBeNull();expect(text).not.toContain('Atualizar cotação');expect(fixture.nativeElement.querySelector('h1')?.textContent).toBe('Ações');expect(fixture.nativeElement.querySelector('a[aria-label="Ver detalhes de AAPL"]')).toBeTruthy();});
 it('does not search while typing and clears without GET',()=>{component().searchForm.controls.ticker.setValue('petr4');component().searchForm.controls.mercado.setValue('BRASIL');fixture.detectChanges();expect(service.buscarPorTickerEMercado).not.toHaveBeenCalled();component().clearSearch();expect(service.listar).toHaveBeenCalledTimes(1);expect(fixture.nativeElement.textContent).toContain('AAPL');});
 it('searches only on submit and navigates with transient DTO',()=>{component().searchForm.controls.ticker.setValue(' petr4 ');component().searchForm.controls.mercado.setValue('BRASIL');component().search();expect(service.buscarPorTickerEMercado).toHaveBeenCalledWith('PETR4','BRASIL');expect(TestBed.inject(Router).navigate).toHaveBeenCalledWith([1],expect.objectContaining({info:{acao:BR}}));});
 it('validates both search fields without request',()=>{component().search();fixture.detectChanges();expect(service.buscarPorTickerEMercado).not.toHaveBeenCalled();expect(fixture.nativeElement.querySelectorAll('mat-error')).toHaveLength(2);});
 it('preserves collection and contextualizes local 404 without classifying provider ticker',()=>{service.buscarPorTickerEMercado.mockReturnValueOnce(throwError(()=>failure(404,null,'Registro ausente')));component().searchForm.controls.ticker.setValue('XPTO');component().searchForm.controls.mercado.setValue('BRASIL');component().search();fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Ação não encontrada para o ticker e mercado');expect(fixture.nativeElement.textContent).toContain('AAPL');});
 it('renders empty, errors, loading and performs a real retry',()=>{service.listar.mockReturnValueOnce(of([]));component().load();fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Nenhuma ação cadastrada');service.listar.mockReturnValueOnce(throwError(()=>failure(500,null,'Falha ao listar'))).mockReturnValueOnce(of([BR]));component().load();fixture.detectChanges();expect(fixture.nativeElement.textContent).toContain('Falha ao listar');const retry=[...fixture.nativeElement.querySelectorAll('button')].find((button:HTMLButtonElement)=>button.textContent?.includes('Tentar carregar')) as HTMLButtonElement;retry.click();fixture.detectChanges();expect(service.listar).toHaveBeenCalledTimes(4);expect(fixture.nativeElement.textContent).toContain('PETR4');service.listar.mockReturnValueOnce(new Subject<AcaoResponse[]>());component().load();fixture.detectChanges();expect(fixture.nativeElement.querySelector('[role="status"]')?.textContent).toContain('Carregando ações');});
 it('announces an explicit search and blocks a concurrent submit',()=>{const pending=new Subject<AcaoResponse>();service.buscarPorTickerEMercado.mockReturnValueOnce(pending);component().searchForm.controls.ticker.setValue('PETR4');component().searchForm.controls.mercado.setValue('BRASIL');component().search();component().search();fixture.detectChanges();expect(service.buscarPorTickerEMercado).toHaveBeenCalledTimes(1);expect(fixture.nativeElement.textContent).toContain('Buscando ação');});
});
